Added solutions for homework (week 2) tasks
sarunaspra/CoherentSolutionsAcademy pull request #2
Opened 2021-11-28 22:27 UTC by sarunaspra

2021-12-06 09:12 UTC, IgorKheidorov requested changes
Good job for the beginning, small changes are required

2021-12-06 09:12 UTC, IgorKheidorov commented on HomeworkWeekTwo/Tasks/CheckTernaryNumberForm.cs
> +
Methods InputRangeEndingPoint and InputRangeStartingPoint differs only by output messages, better to create one method like InutRangePoint(string message). This methods totally do the same task- ask and process the integer value

2021-12-07 09:45 UTC, sarunaspra commented on HomeworkWeekTwo/Tasks/CheckTernaryNumberForm.cs
> +            {
When it is beneficial to use .Equals instead of ==? With bigger strings?

2021-12-20 08:50 UTC, IgorKheidorov approved these changes

2021-12-20 12:30 UTC, merged