Added Training management system exercise solution
sarunaspra/CoherentSolutionsAcademy pull request #4
Opened 2021-12-24 17:20 UTC by sarunaspra

I wanted to ask about my whole project structure. I'm not sure, if I am doing this right, I tried to separate Homework2 Task1 and Task2 to separate branches, to create two pull requests. Is my current approach correct?

2022-01-06 14:04 UTC, radislavkireev requested changes

2022-01-06 14:04 UTC, radislavkireev commented on Homework2/TrainingManagementSystem/Entities/Training.cs
> +            TrainingActivities = cloneableTraining.TrainingActivities;
The cloning should be deep clone, meaning that TrainingActivities should be cloned as well, not just passed asreferences. 
sorry if the requirements were misleading.

2022-01-17 10:09 UTC, radislavkireev requested changes

2022-01-17 10:09 UTC, radislavkireev commented on Homework2/TrainingManagementSystem/Entities/Training.cs
> +            TrainingActivities = cloneableTraining.TrainingActivities;
Deep cloning means that each item of TrainingActivities is cloned. 
Current implementation uses the same instance of TrainingActivities 

How it should be:
```
Training Clone()
{
     Training clone = new Training(this.Description);
     foreach(var item in this.TrainingActivities)
     {
         clone.Add(item.Clone());
     }
     return clone;
}
// I do not provide a code for cloning PracticalLesson / Lecture
```

2022-01-18 07:41 UTC, sarunaspra commented on Homework2/TrainingManagementSystem/Entities/Training.cs
> +            TrainingActivities = cloneableTraining.TrainingActivities;
Thank you for the explanation. I fixed my deep cloning solution according to your code written above. My approach differs a little bit, because I use an array to store lectures / practicalLessons, not list.

2022-01-18 07:43 UTC, sarunaspra commented on Homework2/TrainingManagementSystem/Entities/PracticalLesson.cs
> -            Description = description;
My bad, 20th line should not have been deleted. I'll fix it.

2022-01-18 11:42 UTC, rkireevLT approved these changes

2022-01-23 12:08 UTC, merged