Adding solution for task PianoKeys
sarunaspra/CoherentSolutionsAcademy pull request #5
Opened 2022-01-02 18:42 UTC by sarunaspra

Not sure if I fully fullfiled task requirements, because, for example, in my solution case Key(Note.C, Accidental.Sharp, Octave.First) and Key(Note.D, Accidental.Flat, Octave.First) are not equal, but according to the task description they should be equal.

2022-01-02 18:51 UTC, sarunaspra commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +            int AccidentalComparisionResult = Accidental.CompareTo(other.Accidental);
Sorry, my mistake with the variable naming, I'll fix it.

2022-01-18 11:56 UTC, radislavkireev requested changes

2022-01-18 11:56 UTC, radislavkireev commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +        public int CompareTo(PianoKey other)
Check only Octave - pls see requirements https://drive.google.com/drive/folders/1lbNAaiMZsgLovlXhq2n9z_f-arH8pQ4Y 

```
// C# of the first octave
Key c = new Key(Note.C, Accidental.Sharp, Octave.First);
Console.WriteLine(c); // C# (1)
// D flat of the first octave
Key d = new Key(Note.D, Accidental.Flat, Octave.First);
Console.WriteLine(c.Equals(d)); // True, is the same key!
```

2022-01-18 11:56 UTC, radislavkireev commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +                throw new ArgumentException("Cannot compare to given object type");
just return false instead

2022-01-18 11:56 UTC, radislavkireev commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +            if (!(obj is PianoKey))
Add the case when obj is null

2022-01-19 06:39 UTC, sarunaspra commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +        public int CompareTo(PianoKey other)
So if Octaves of Keys coincide, the result is that Keys are equal?

2022-01-22 16:12 UTC, radislavkireev approved these changes

2022-01-22 16:12 UTC, radislavkireev commented on Homework3/PianoKeys/Structures/PianoKey.cs
> +        public int CompareTo(PianoKey other)
Lets keep it as is, I have no certain understanding in the domain, how to compare pianos?

2022-01-23 12:01 UTC, merged